-- 优惠券模板表
CREATE TABLE IF NOT EXISTS `coupon_template` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `name` varchar(100) NOT NULL COMMENT '优惠券名称',
  `type` int NOT NULL DEFAULT 1 COMMENT '类型：1-满减券，2-折扣券，3-现金券',
  `value` decimal(10,2) NOT NULL COMMENT '优惠值（满减金额/折扣比例0.8/现金金额）',
  `min_amount` decimal(10,2) DEFAULT 0.00 COMMENT '最低消费门槛',
  `max_discount` decimal(10,2) DEFAULT NULL COMMENT '最大优惠金额（折扣券用）',
  `point_cost` int NOT NULL COMMENT '兑换所需积分',
  `total_stock` int NOT NULL DEFAULT 0 COMMENT '总库存',
  `remaining_stock` int NOT NULL DEFAULT 0 COMMENT '剩余库存',
  `per_user_limit` int DEFAULT 1 COMMENT '每人限领数量',
  `valid_days` int NOT NULL DEFAULT 30 COMMENT '有效天数（从领取日开始）',
  `start_time` datetime DEFAULT NULL COMMENT '有效期开始时间',
  `end_time` datetime DEFAULT NULL COMMENT '有效期结束时间',
  `status` int NOT NULL DEFAULT 1 COMMENT '状态：0-禁用，1-启用',
  `description` varchar(500) DEFAULT NULL COMMENT '使用说明',
  `is_delete` int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  KEY `idx_status` (`status`),
  KEY `idx_is_delete` (`is_delete`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='优惠券模板表';

-- 用户优惠券表
CREATE TABLE IF NOT EXISTS `user_coupon` (
  `id` bigint NOT NULL COMMENT '主键ID',
  `user_id` bigint NOT NULL COMMENT '用户ID',
  `template_id` bigint NOT NULL COMMENT '优惠券模板ID',
  `coupon_no` varchar(32) NOT NULL COMMENT '优惠券编号',
  `type` int NOT NULL COMMENT '类型：1-满减券，2-折扣券，3-现金券',
  `value` decimal(10,2) NOT NULL COMMENT '优惠值',
  `min_amount` decimal(10,2) DEFAULT 0.00 COMMENT '最低消费门槛',
  `max_discount` decimal(10,2) DEFAULT NULL COMMENT '最大优惠金额',
  `status` int NOT NULL DEFAULT 0 COMMENT '状态：0-未使用，1-已使用，2-已过期',
  `order_id` bigint DEFAULT NULL COMMENT '使用的订单ID',
  `used_time` datetime DEFAULT NULL COMMENT '使用时间',
  `start_time` datetime NOT NULL COMMENT '有效期开始时间',
  `end_time` datetime NOT NULL COMMENT '有效期结束时间',
  `point_cost` int NOT NULL COMMENT '兑换消耗的积分',
  `is_delete` int NOT NULL DEFAULT 0 COMMENT '逻辑删除',
  `create_time` datetime DEFAULT CURRENT_TIMESTAMP COMMENT '领取时间',
  `update_time` datetime DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_coupon_no` (`coupon_no`),
  KEY `idx_user_id` (`user_id`),
  KEY `idx_status` (`status`),
  KEY `idx_end_time` (`end_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='用户优惠券表';
